<?php
declare(strict_types = 1);

use NatOkpe\Wp\Plugin\TranquilSetup\Engine;

/* Config: Engine */
return [
    'show_admin_bar' => false,

    'admin_footer_text' => sprintf(
        'Need help? &mdash; '
        . '<a %4$s href="mailto:%1$s">Email</a> | '
        . '<a %4$s href="tel:%2$s">Call</a> | '
        . '<a %4$s href="https://api.whatsapp.com/send?phone=%3$s">WhatsApp</a>',
        esc_attr('support@nat.com.ng'),
        esc_attr('+234-703-929-0234'),
        esc_attr('2347039290234'),
        'target="_blank" rel="noopener noreferrer"'
    ),

    'update_footer' => sprintf(
        '<a %s href="%s">Create a website</a>',
        'target="_blank" rel="noopener noreferrer"',
        esc_attr('https://nat.com.ng')
    ),

    'upload_mimes_absolute' => true,

    'upload_mimes' => [
        'jpg|jpeg|jpe'                 => 'image/jpeg',
        'gif'                          => 'image/gif',
        'png'                          => 'image/png',
        'bmp'                          => 'image/bmp',
        'tiff|tif'                     => 'image/tiff',
        'webp'                         => 'image/webp',
        'ico|cur'                      => 'image/x-icon',
        'heic'                         => 'image/heic',
        'asf|asx'                      => 'video/x-ms-asf',
        'avif'                         => 'image/avif',
        'wmv'                          => 'video/x-ms-wmv',
        'wmx'                          => 'video/x-ms-wmx',
        'wm'                           => 'video/x-ms-wm',
        'avi'                          => 'video/avi',
        'divx'                         => 'video/divx',
        'flv'                          => 'video/x-flv',
        'mov|qt'                       => 'video/quicktime',
        'mpeg|mpg|mpe'                 => 'video/mpeg',
        'mp4|m4v'                      => 'video/mp4',
        'ogv'                          => 'video/ogg',
        'webm'                         => 'video/webm',
        'mkv'                          => 'video/x-matroska',
        '3gp|3gpp'                     => 'video/3gpp',
        '3g2|3gp2'                     => 'video/3gpp2',
        'txt|asc|c|cc|h|srt'           => 'text/plain',
        'csv'                          => 'text/csv',
        'tsv'                          => 'text/tab-separated-values',
        'ics'                          => 'text/calendar',
        'rtx'                          => 'text/richtext',
        'css'                          => 'text/css',
        'htm|html'                     => 'text/html',
        'vtt'                          => 'text/vtt',
        'dfxp'                         => 'application/ttaf+xml',
        'mp3|m4a|m4b'                  => 'audio/mpeg',
        'aac'                          => 'audio/aac',
        'ra|ram'                       => 'audio/x-realaudio',
        'wav'                          => 'audio/wav',
        'ogg|oga'                      => 'audio/ogg',
        'flac'                         => 'audio/flac',
        'mid|midi'                     => 'audio/midi',
        'wma'                          => 'audio/x-ms-wma',
        'wax'                          => 'audio/x-ms-wax',
        'mka'                          => 'audio/x-matroska',
        'rtf'                          => 'application/rtf',
        'js'                           => 'application/javascript',
        'pdf'                          => 'application/pdf',
        'class'                        => 'application/java',
        'tar'                          => 'application/x-tar',
        'zip'                          => 'application/zip',
        'gz|gzip'                      => 'application/x-gzip',
        'rar'                          => 'application/rar',
        '7z'                           => 'application/x-7z-compressed',
        'psd'                          => 'application/octet-stream',
        'xcf'                          => 'application/octet-stream',
        'doc'                          => 'application/msword',
        'pot|pps|ppt'                  => 'application/vnd.ms-powerpoint',
        'wri'                          => 'application/vnd.ms-write',
        'xla|xls|xlt|xlw'              => 'application/vnd.ms-excel',
        'mdb'                          => 'application/vnd.ms-access',
        'mpp'                          => 'application/vnd.ms-project',
        'docx'                         => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'docm'                         => 'application/vnd.ms-word.document.macroEnabled.12',
        'dotx'                         => 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
        'dotm'                         => 'application/vnd.ms-word.template.macroEnabled.12',
        'xlsx'                         => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'xlsm'                         => 'application/vnd.ms-excel.sheet.macroEnabled.12',
        'xlsb'                         => 'application/vnd.ms-excel.sheet.binary.macroEnabled.12',
        'xltx'                         => 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
        'xltm'                         => 'application/vnd.ms-excel.template.macroEnabled.12',
        'xlam'                         => 'application/vnd.ms-excel.addin.macroEnabled.12',
        'pptx'                         => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'pptm'                         => 'application/vnd.ms-powerpoint.presentation.macroEnabled.12',
        'ppsx'                         => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
        'ppsm'                         => 'application/vnd.ms-powerpoint.slideshow.macroEnabled.12',
        'potx'                         => 'application/vnd.openxmlformats-officedocument.presentationml.template',
        'potm'                         => 'application/vnd.ms-powerpoint.template.macroEnabled.12',
        'ppam'                         => 'application/vnd.ms-powerpoint.addin.macroEnabled.12',
        'sldx'                         => 'application/vnd.openxmlformats-officedocument.presentationml.slide',
        'sldm'                         => 'application/vnd.ms-powerpoint.slide.macroEnabled.12',
        'svg|svgz'                     => 'image/svg+xml',
        'onetoc|onetoc2|onetmp|onepkg' => 'application/onenote',
        'oxps'                         => 'application/oxps',
        'xps'                          => 'application/vnd.ms-xpsdocument',
        'odt'                          => 'application/vnd.oasis.opendocument.text',
        'odp'                          => 'application/vnd.oasis.opendocument.presentation',
        'ods'                          => 'application/vnd.oasis.opendocument.spreadsheet',
        'odg'                          => 'application/vnd.oasis.opendocument.graphics',
        'odc'                          => 'application/vnd.oasis.opendocument.chart',
        'odb'                          => 'application/vnd.oasis.opendocument.database',
        'odf'                          => 'application/vnd.oasis.opendocument.formula',
        'wp|wpd'                       => 'application/wordperfect',
        'key'                          => 'application/vnd.apple.keynote',
        'numbers'                      => 'application/vnd.apple.numbers',
        'pages'                        => 'application/vnd.apple.pages',
    ],

    'query_vars' => [
    ],
];
