<?php
declare(strict_types = 1);

use NatOkpe\Wp\Plugin\TranquilSetup\Engine;

/* Config: Post types */
return [
    'event' => [
        'label' => 'Events',
        'labels' => [
            'name' => 'Events',
            'singular_name' => 'Event',
            'add_new' => 'Add New Event',
            'add_new_item' => 'Add New Event',
            'edit_item' => 'Edit Event',
            'new_item' => 'New Event',
            'view_item' => 'View Event',
            'view_items' => 'View Events',
            'search_items' => 'Search Events',
            'not_found' => 'No events found',
            'not_found_in_trash' => 'No events found in Trash',
            'parent_item_colon' => 'Parent Event:',
            'all_items' => 'All Events',
            'archives' => 'Event Archives',
            'attributes' => 'Event Attributes',
            'insert_into_item' => 'Insert into event',
            'uploaded_to_this_item' => 'Uploaded to this event',
            'featured_image' => 'Featured image',
            'set_featured_image' => 'Set featured image',
            'remove_featured_image' => 'Remove featured image',
            'use_featured_image' => 'Use as featured image',
            'menu_name' => 'Events',
            'filter_items_list' => 'Filter events list',
            'filter_by_date' => 'Filter by date',
            'items_list_navigation' => 'Events list navigation',
            'items_list' => 'Events list',
            'item_published' => 'Event published.',
            'item_published_privately' => 'Event published privately.',
            'item_reverted_to_draft' => 'Event reverted to draft.',
            'item_trashed' => 'Event trashed.',
            'item_scheduled' => 'Event scheduled.',
            'item_updated' => 'Event updated.',
            'item_link' => 'Event Link',
            'item_link_description' => 'A link to a event.',
        ],
        'description' => 'Events',
        'public' => true,
        'hierarchical' => false,
        'exclude_from_search' => false,
        'publicly_queryable' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_nav_menus' => true,
        'show_in_admin_bar' => true,
        'show_in_rest' => true,
        'menu_position' => 20,
        'menu_icon' => 'dashicons-calendar',
        'capability_type' => ['event', 'events'],
        // 'capabilities' => [],
        'map_meta_cap' => true,
        'supports' => [
            'title',
            'editor',
            // 'trackbacks',
            // 'author',
            'excerpt',
            'page-attributes',
            'thumbnail',
        ],
        'taxonomies' => [
            'event-location',
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var ' => '',
        'can_export' => true,
        'delete_with_user' => false,
    ],

    'person' => [
        'label' => 'Persons',
        'labels' => [
            'name' => 'People',
            'singular_name' => 'Person',
            'add_new' => 'Add New Person',
            'add_new_item' => 'Add New Person',
            'edit_item' => 'Edit Person',
            'new_item' => 'New Person',
            'view_item' => 'View Person',
            'view_items' => 'View Persons',
            'search_items' => 'Search Persons',
            'not_found' => 'No persons found',
            'not_found_in_trash' => 'No persons found in Trash',
            'parent_item_colon' => 'Parent Person:',
            'all_items' => 'All Persons',
            'archives' => 'Person Archives',
            'attributes' => 'Person Attributes',
            'insert_into_item' => 'Insert into person',
            'uploaded_to_this_item' => 'Uploaded to this person',
            'featured_image' => 'Featured image',
            'set_featured_image' => 'Set featured image',
            'remove_featured_image' => 'Remove featured image',
            'use_featured_image' => 'Use as featured image',
            'menu_name' => 'People',
            'filter_items_list' => 'Filter persons list',
            'filter_by_date' => 'Filter by date',
            'items_list_navigation' => 'Persons list navigation',
            'items_list' => 'Persons list',
            'item_published' => 'Person published.',
            'item_published_privately' => 'Person published privately.',
            'item_reverted_to_draft' => 'Person reverted to draft.',
            'item_trashed' => 'Person trashed.',
            'item_scheduled' => 'Person scheduled.',
            'item_updated' => 'Person updated.',
            'item_link' => 'Person Link',
            'item_link_description' => 'A link to a person.',
        ],
        'description' => 'Persons',
        'public' => true,
        'hierarchical' => false,
        'exclude_from_search' => true,
        'publicly_queryable' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_nav_menus' => true,
        'show_in_admin_bar' => true,
        'show_in_rest' => true,
        'menu_position' => 20,
        'menu_icon' => 'dashicons-groups',
        'capability_type' => ['person', 'persons'],
        // 'capabilities' => [],
        'map_meta_cap' => true,
        'supports' => [
            // 'title',
            // 'editor',
            // 'trackbacks',
            // 'author',
            // 'excerpt',
            'page-attributes',
            'thumbnail',
        ],
        'taxonomies' => [
            'person-group', 'person-role'
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var ' => '',
        'can_export' => true,
        'delete_with_user' => false,
    ],
    
    'faq' => [
        'label'  => 'FAQs',
        'labels' => [
            'name'                     => 'FAQs',
            'singular_name'            => 'FAQ',
            'add_new'                  => 'Add New FAQ',
            'add_new_item'             => 'Add New FAQ',
            'edit_item'                => 'Edit FAQ',
            'new_item'                 => 'New FAQ',
            'view_item'                => 'View FAQ',
            'view_items'               => 'View FAQs',
            'search_items'             => 'Search FAQs',
            'not_found'                => 'No faqs found',
            'not_found_in_trash'       => 'No faqs found in Trash',
            'parent_item_colon'        => 'Parent FAQ:',
            'all_items'                => 'All FAQs',
            'archives'                 => 'FAQ Archives',
            'attributes'               => 'FAQ Attributes',
            'insert_into_item'         => 'Insert into faq',
            'uploaded_to_this_item'    => 'Uploaded to this faq',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'FAQs',
            'filter_items_list'        => 'Filter faqs list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'FAQs list navigation',
            'items_list'               => 'FAQs list',
            'item_published'           => 'FAQ published.',
            'item_published_privately' => 'FAQ published privately.',
            'item_reverted_to_draft'   => 'FAQ reverted to draft.',
            'item_trashed'             => 'FAQ trashed.',
            'item_scheduled'           => 'FAQ scheduled.',
            'item_updated'             => 'FAQ updated.',
            'item_link'                => 'FAQ Link',
            'item_link_description'    => 'A link to a faq.',
        ],
        'description'         => 'Frequently Asked Questions (FAQs)',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => false,
        'publicly_queryable'  => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => true,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'menu_icon'        => 'dashicons-editor-help',
        'capability_type'     => ['faq', 'faqs'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => [
            'title',
            'editor',
            // 'trackbacks',
            'author',
            // 'excerpt',
            // 'page-attributes',
            // 'thumbnail',
        ],
        'taxonomies' => [
            'faq-topic'
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var'        => '',
        'can_export'       => true,
        'delete_with_user' => false,
    ],
];
