<?php
declare(strict_types = 1);

use NatOkpe\Wp\Plugin\ImpactSetup\Engine;

return [
    'senior_administrator' => [ // Class I
        'name' => 'Senior Administrator',
        'cap' => [
            'update_themes',
            'delete_others_pages',
            'delete_others_posts',
            'delete_pages',
            'delete_posts',
            'delete_private_pages',
            'delete_private_posts',
            'delete_published_pages',
            'delete_published_posts',
            'edit_dashboard',
            'edit_others_pages',
            'edit_others_posts',
            'edit_pages',
            'edit_posts',
            'edit_private_pages',
            'edit_private_posts',
            'edit_published_pages',
            'edit_published_posts',
            'edit_theme_options',
            'export',
            'import',
            'manage_categories',
            'manage_links',
            'moderate_comments',
            'promote_users',
            'publish_pages',
            'publish_posts',
            'read_private_pages',
            'read_private_posts',

            'read',

            'create Patterns',
            'edit Patterns',
            'read Patterns',
            'delete Patterns',

            'upload_files',
            'customize',

            'list_users',
            'edit_users',
            'add_users',
            'create_users',
            'remove_users',
            'delete_users',

            'unfiltered_html',
            'unfiltered_upload',

            'edit_event',
            'read_event',
            'delete_event',
            'edit_events',
            'edit_others_events',
            'delete_events',
            'publish_events',
            'read_private_events',
            'delete_private_events',
            'delete_published_events',
            'delete_others_events',
            'edit_private_events',
            'edit_published_events',
            'edit_events',

            'edit_person',
            'read_person',
            'delete_person',
            'edit_persons',
            'edit_others_persons',
            'delete_persons',
            'publish_persons',
            'read_private_persons',
            'delete_private_persons',
            'delete_published_persons',
            'delete_others_persons',
            'edit_private_persons',
            'edit_published_persons',
            'edit_persons',

            'edit_faq',
            'read_faq',
            'delete_faq',
            'edit_faqs',
            'edit_others_faqs',
            'delete_faqs',
            'publish_faqs',
            'read_private_faqs',
            'delete_private_faqs',
            'delete_published_faqs',
            'delete_others_faqs',
            'edit_private_faqs',
            'edit_published_faqs',
            'edit_faqs',
        ],
    ],

    'junior_administrator' => [ // Class II
        'name' => 'Junior Administrator',
        'cap' => [
            'edit_dashboard',
            'edit_others_pages',
            'edit_others_posts',
            'edit_pages',
            'edit_posts',
            'edit_private_pages',
            'edit_private_posts',
            'edit_published_pages',
            'edit_published_posts',
            'manage_categories',
            'manage_links',
            'moderate_comments',
            'publish_pages',
            'publish_posts',
            'read_private_pages',
            'read_private_posts',
            'read',
            'create Patterns',
            'edit Patterns',
            'read Patterns',
            'delete Patterns',
            'list_users',
            'edit_users',

            'upload_files',
            'unfiltered_html',
            'unfiltered_upload',

            'edit_event',
            'read_event',
            'edit_events',
            'edit_others_events',
            'publish_events',
            'read_private_events',
            'edit_private_events',
            'edit_published_events',
            'edit_events',

            'edit_person',
            'read_person',
            'edit_persons',
            'edit_others_persons',
            'publish_persons',
            'read_private_persons',
            'edit_private_persons',
            'edit_published_persons',
            'edit_persons',

            'edit_faq',
            'read_faq',
            'edit_faqs',
            'edit_others_faqs',
            'publish_faqs',
            'read_private_faqs',
            'edit_private_faqs',
            'edit_published_faqs',
            'edit_faqs',
        ],
    ],

    'content-editor' => [
        'name' => 'Editor',
        'cap' => [
            'read',

            'read Patterns',
            'upload_files',

            'delete_others_posts',
            'delete_posts',
            'delete_private_posts',
            'delete_published_posts',
            'edit_dashboard',
            'edit_others_posts',
            'edit_posts',
            'edit_private_posts',
            'edit_published_posts',
            'manage_categories',
            'manage_links',
            'moderate_comments',
            'publish_posts',
            'read_private_posts',

            'edit_event',
            'read_event',
            'delete_event',
            'edit_events',
            'edit_others_events',
            'delete_events',
            'publish_events',
            'read_private_events',
            'delete_private_events',
            'delete_published_events',
            'delete_others_events',
            'edit_private_events',
            'edit_published_events',
            'edit_events',
        ],
    ],
];

/* Multisite Super Admins have, by default, all capabilities. The following Multisite-only capabilities are therefore only available to Super Admins: */
// 'create_sites',
// 'delete_sites',
// 'manage_network',
// 'manage_sites',
// 'manage_network_users',
// 'manage_network_plugins',
// 'manage_network_themes',
// 'manage_network_options',
// 'upgrade_network',
// 'setup_network',

/* All administrators have the following capabilities: */
// 'activate_plugins',
// 'delete_others_pages',
// 'delete_others_posts',
// 'delete_pages',
// 'delete_posts',
// 'delete_private_pages',
// 'delete_private_posts',
// 'delete_published_pages',
// 'delete_published_posts',
// 'edit_dashboard',
// 'edit_others_pages',
// 'edit_others_posts',
// 'edit_pages',
// 'edit_posts',
// 'edit_private_pages',
// 'edit_private_posts',
// 'edit_published_pages',
// 'edit_published_posts',
// 'edit_theme_options',
// 'export',
// 'import',
// 'list_users',
// 'manage_categories',
// 'manage_links',
// 'manage_options',
// 'moderate_comments',
// 'promote_users',
// 'publish_pages',
// 'publish_posts',
// 'read_private_pages',
// 'read_private_posts',
// 'read',
// 'create Patterns',
// 'edit Patterns',
// 'read Patterns',
// 'delete Patterns',
// 'remove_users',
// 'switch_themes',
// 'upload_files',
// 'customize',
// 'delete_site',

/* Only Administrators of single site installations have the following capabilities. In Multisite, only the Super Admin has these abilities: */
// 'update_core',
// 'update_plugins',
// 'update_themes',
// 'install_plugins',
// 'install_themes',
// 'delete_themes',
// 'delete_plugins',
// 'edit_plugins',
// 'edit_themes',
// 'edit_files',
// 'edit_users',
// 'add_users',
// 'create_users',
// 'delete_users',
// 'unfiltered_html',

// 'level_0'

// 'unfiltered_upload',

// 'edit_event',
// 'read_event',
// 'delete_event',
// 'edit_events',
// 'edit_others_events',
// 'delete_events',
// 'publish_events',
// 'read_private_events',
// 'delete_private_events',
// 'delete_published_events',
// 'delete_others_events',
// 'edit_private_events',
// 'edit_published_events',
// 'edit_events',

// 'edit_person',
// 'read_person',
// 'delete_person',
// 'edit_persons',
// 'edit_others_persons',
// 'delete_persons',
// 'publish_persons',
// 'read_private_persons',
// 'delete_private_persons',
// 'delete_published_persons',
// 'delete_others_persons',
// 'edit_private_persons',
// 'edit_published_persons',
// 'edit_persons',

// 'edit_faq',
// 'read_faq',
// 'delete_faq',
// 'edit_faqs',
// 'edit_others_faqs',
// 'delete_faqs',
// 'publish_faqs',
// 'read_private_faqs',
// 'delete_private_faqs',
// 'delete_published_faqs',
// 'delete_others_faqs',
// 'edit_private_faqs',
// 'edit_published_faqs',
// 'edit_faqs',