<?php
declare(strict_types = 1);

/* Config: Taxonomies */
return [
    'person-group' => [
        'object_type' => 'person',
        'args' => [
            'label'        => _x('Groups', 'group taxonomy general name'),
            'labels' => [
                'name' => _x('Groups', 'group taxonomy general name'),
                'singular_name' => _x('Group', 'group taxonomy singular name'),
                'menu_name' => __('Groups', 'natokpe'),
                'all_items' => __('All Groups', 'natokpe'),
                'edit_item' => __('Edit Group', 'natokpe'),
                'view_item' => __('View Group', 'natokpe'),
                'update_item' => __('Update Group', 'natokpe'),
                'add_new_item' => __('Add New Group', 'natokpe'),
                'new_item_name' => __('New Group Name', 'natokpe'),
                'parent_item' => __('Parent Group', 'natokpe'),
                'parent_item_colon' => __('Parent Group:', 'natokpe'),
                'search_items' => __('Search Groups', 'natokpe'),
                'popular_items' => __('Popular Groups', 'natokpe'),
                'separate_items_with_commas' => __('Separate groups with commas', 'natokpe'),
                'add_or_remove_items' => __('Add or remove groups', 'natokpe'),
                'choose_from_most_used' => __('Choose from most used group', 'natokpe'),
                'not_found' => __('No group found.', 'natokpe'),
                'back_to_items' => __('← Back to groups', 'natokpe'),
            ],
            'description' => __('Groups provide a means of categorising people.', 'natokpe'),
            'public' => true,
            'publicly_queryable' => false,
            'hierarchical' => true,
            'show_ui' => true,
            'show_in_menu' => true,
            'show_in_nav_menus' => true,
            'show_in_rest' => true,
            'show_tagcloud' => false,
            'show_in_quick_edit' => false,
            'show_admin_column' => true,
            // 'meta_box_cb' => function () {},
            // 'meta_box_sanitize_cb' => function () {},
            'capabilities' => [
                'manage_terms' => 'edit_persons',
                'edit_terms' => 'edit_persons',
                'delete_terms' => 'delete_persons',
                'assign_terms' => 'edit_persons',
            ],
            'rewrite' => [
                // 'slug' => 'group',
                'with_front' => false,
            ],
            // 'query_var' => 'group',
            'default_term' => [
                'name' => 'Member',
                'slug' => 'member',
                'description' => 'Default group',
            ],
            // 'sort' => null,
            // 'args' => [],
        ],
    ],

    'person-role' => [
        'object_type' => 'person',
        'args' => [
            'label'        => _x('Roles', 'role taxonomy general name'),
            'labels' => [
                'name' => _x('Roles', 'role taxonomy general name'),
                'singular_name' => _x('Role', 'role taxonomy singular name'),
                'menu_name' => __('Roles', 'natokpe'),
                'all_items' => __('All Roles', 'natokpe'),
                'edit_item' => __('Edit Role', 'natokpe'),
                'view_item' => __('View Role', 'natokpe'),
                'update_item' => __('Update Role', 'natokpe'),
                'add_new_item' => __('Add New Role', 'natokpe'),
                'new_item_name' => __('New Role Name', 'natokpe'),
                'parent_item' => __('Parent Role', 'natokpe'),
                'parent_item_colon' => __('Parent Role:', 'natokpe'),
                'search_items' => __('Search Roles', 'natokpe'),
                'popular_items' => __('Popular Roles', 'natokpe'),
                'separate_items_with_commas' => __('Separate roles with commas', 'natokpe'),
                'add_or_remove_items' => __('Add or remove roles', 'natokpe'),
                'choose_from_most_used' => __('Choose from most used role', 'natokpe'),
                'not_found' => __('No role found.', 'natokpe'),
                'back_to_items' => __('← Back to roles', 'natokpe'),
            ],
            'description' => __('Roles specifies roles of members of natokpe as aligned with their responsibilities within the organisation.', 'natokpe'),
            'public' => true,
            'publicly_queryable' => false,
            'hierarchical' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'show_in_nav_menus' => true,
            'show_in_rest' => true,
            'show_tagcloud' => false,
            'show_in_quick_edit' => false,
            'show_admin_column' => true,
            // 'meta_box_cb' => function () {},
            // 'meta_box_sanitize_cb' => function () {},
            'capabilities' => [
                'manage_terms' => 'edit_persons',
                'edit_terms' => 'edit_persons',
                'delete_terms' => 'delete_persons',
                'assign_terms' => 'edit_persons',
            ],
            'rewrite' => [
                // 'slug' => 'role',
                'with_front' => false,
            ],
            // 'query_var' => 'role',
            // 'default_term' => [
            //     'name' => 'Member',
            //     'slug' => 'member',
            //     'description' => 'Default role',
            // ],
            // 'sort' => null,
            // 'args' => [],
        ],
    ],

    'faq-topic' => [
        'object_type' => 'faq',
        'args' => [
            'label'        => _x('Topics', 'topic taxonomy general name'),
            'labels' => [
                'name' => _x('Topics', 'topic taxonomy general name'),
                'singular_name' => _x('Topic', 'topic taxonomy singular name'),
                'menu_name' => __('Topics', 'natokpe'),
                'all_items' => __('All Topics', 'natokpe'),
                'edit_item' => __('Edit Topic', 'natokpe'),
                'view_item' => __('View Topic', 'natokpe'),
                'update_item' => __('Update Topic', 'natokpe'),
                'add_new_item' => __('Add New Topic', 'natokpe'),
                'new_item_name' => __('New Topic Name', 'natokpe'),
                'parent_item' => __('Parent Topic', 'natokpe'),
                'parent_item_colon' => __('Parent Topic:', 'natokpe'),
                'search_items' => __('Search Topics', 'natokpe'),
                'popular_items' => __('Popular Topics', 'natokpe'),
                'separate_items_with_commas' => __('Separate topics with commas', 'natokpe'),
                'add_or_remove_items' => __('Add or remove topics', 'natokpe'),
                'choose_from_most_used' => __('Choose from most used topic', 'natokpe'),
                'not_found' => __('No topic found.', 'natokpe'),
                'back_to_items' => __('← Back to topics', 'natokpe'),
            ],
            'description' => __('Topics specifies roles of members of natokpe as aligned with their responsibilities within the organisation.', 'natokpe'),
            'public' => true,
            'publicly_queryable' => true,
            'hierarchical' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'show_in_nav_menus' => true,
            'show_in_rest' => true,
            'show_tagcloud' => false,
            'show_in_quick_edit' => true,
            'show_admin_column' => true,
            // 'meta_box_cb' => function () {},
            // 'meta_box_sanitize_cb' => function () {},
            // 'capabilities' => [
            //     'manage_terms' => 'manage_categories',
            //     'edit_terms' => 'manage_categories',
            //     'delete_terms' => 'manage_categories',
            //     'assign_terms' => 'edit_posts',
            // ],
            'rewrite' => [
                // 'slug' => 'topic',
                'with_front' => false,
            ],
            // 'query_var' => 'topic',
            'default_term' => [
                'name' => 'General',
                'slug' => 'general',
                'description' => 'Default topic',
            ],
            // 'sort' => null,
            // 'args' => [],
        ],
    ],

    'event-location' => [
        'object_type' => 'event',
        'args' => [
            'label'        => _x('Location', 'taxonomy general name'),
            'labels' => [
                'name' => _x('Locations', 'taxonomy general name'),
                'singular_name' => _x('Location', 'location taxonomy singular name'),
                'menu_name' => __('Locations', 'natokpe'),
                'all_items' => __('All Locations', 'natokpe'),
                'edit_item' => __('Edit Location', 'natokpe'),
                'view_item' => __('View Location', 'natokpe'),
                'update_item' => __('Update Location', 'natokpe'),
                'add_new_item' => __('Add New Location', 'natokpe'),
                'new_item_name' => __('New Location Name', 'natokpe'),
                'parent_item' => __('Parent Location', 'natokpe'),
                'parent_item_colon' => __('Parent Location:', 'natokpe'),
                'search_items' => __('Search Locations', 'natokpe'),
                'popular_items' => __('Popular Locations', 'natokpe'),
                'separate_items_with_commas' => __('Separate locations with commas', 'natokpe'),
                'add_or_remove_items' => __('Add or remove locations', 'natokpe'),
                'choose_from_most_used' => __('Choose from most used location', 'natokpe'),
                'not_found' => __('No location found.', 'natokpe'),
                'back_to_items' => __('← Back to locations', 'natokpe'),
            ],
            'description' => __('Locations specifies roles of members of natokpe as aligned with their responsibilities within the organisation.', 'natokpe'),
            'public' => true,
            'publicly_queryable' => true,
            'hierarchical' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'show_in_nav_menus' => true,
            'show_in_rest' => true,
            'show_tagcloud' => false,
            'show_in_quick_edit' => false,
            'show_admin_column' => true,
            // 'meta_box_cb' => function () {},
            // 'meta_box_sanitize_cb' => function () {},
            // 'capabilities' => [
            //     'manage_terms' => 'manage_categories',
            //     'edit_terms' => 'manage_categories',
            //     'delete_terms' => 'manage_categories',
            //     'assign_terms' => 'edit_posts',
            // ],
            'rewrite' => [
                // 'slug' => 'location',
                'with_front' => false,
            ],
            // 'query_var' => 'location',
            // 'default_term' => [
            //     'name' => 'Nigeria',
            //     'slug' => 'nigeria',
            //     'description' => 'Default location',
            // ],
            // 'sort' => null,
            // 'args' => [],
        ],
    ],
];
